### ISSUE TITLE
Question about Python/C++ API Inconsistency

### ISSUE THREAD

**Issue by bhgomes** [TileDB-Inc/TileDB-Py#126]
Is there a reason to have a different name for the TileDB Context in the Python and C++ APIs? In Python it is written as `Ctx` and in C++ it is simply `Context`. I think the API would benefit from being consistent here and hopefully as many other places as possible.

**Comment by bhgomes** [comment]
Also differences like:

|      Topic      |         Python         |      C++     |
|:---------------:|:----------------------:|:------------:|
|      Arrays     | `DenseArray` | `SparseArray` |     `Array`    |
| Key-Value Store |           `KV`           |      `Map`     |
|     Objects     |      `group_create`      | `create_group` |
|      Config     |         ` save`          | `save_to_file` |

**Comment by ihnorton** [comment]
Hi @bhgomes, thanks for the comments.
- not sure about `Ctx`/`Context`
- I believe `KV` vs `Map` was intentional (I asked about it at one point)
- the `create/group` function naming may have been an oversight (different people working on each API)
- `save` vs `save_to_file` -- the specificity of the second one is probably intentional, whereas the first one could be generalized more easily in Python.

Generally speaking our goal is to make the Python interface more Pythonic, not necessarily to follow the C++ API naming conventions. But please do point out any other inconsistencies you find! I'll take a look at these with @jakebolewski tomorrow.

**Comment by ihnorton** [comment]
> goal is to make the Python interface more Pythonic

By the way, toward this end, we recently made `Ctx` an optional keyword argument on TileDB-Py dev branch.

Regarding
> Arrays | DenseArray | SparseArray

There is no `SparseArray` class in C++, only in Python. Instead, the distinction is made in the `ArraySchema` (`TILEDB_SPARSE` vs `TILEDB_DENSE`). For C++, the query functions are the same, and the semantics are similar. It is the user's responsibility to handle the result buffers as-needed for their application. In contrast, for Python
- indexing a `DenseArray` returns a shaped NumPy ndarray,
- indexing a `SparseArray` returns a 1D array of values per-attribute, with a separate coordinates array

**Comment by bhgomes** [comment]
Thank you @ihnorton for your response. I had guessed that the goal would be to make the interfaces more Pythonic instead of just ported C++, but I just wanted to point out some of the namings that I thought were a bit strange, like not using the full word for the `Ctx` class. 

> By the way, toward this end, we recently made Ctx an optional keyword argument on TileDB-Py dev branch.

How will this affect the way the user thinks about the TileDB context? What would it mean to have multiple contexts? What kind of use cases are there for this exposed interface? I couldn't find anything very instructive on this point on the documentation except for possibly [custom error handling](https://docs.tiledb.io/en/stable/c++-api.html#_CPPv4NK6tiledb7Context12handle_errorEi).

As for the Array naming, I just read it incorrectly, and I agree/understand your comment above.

**Comment by ihnorton** [comment]
> How will this affect the way the user thinks about the TileDB context? What would it mean to have multiple contexts?

This is under-documented at this point, so I will add some docs. A `Context` does have logging and error-handling, but more importantly, a context holds a thread pool and the tile cache.

> What kind of use cases are there for this exposed interface?

So far I think multiple contexts are mainly used with the C++ API in a multi-threaded, batched-read situation. It will likely not be an issue in routine use, especially from Python, but we do need to support multiple contexts in the API. The keyword argument w/ global default fix is an intermediate fix for now, because passing around a super-object to every call felt very un-pythonic (and the same issue was raised independently in the R API: https://github.com/TileDB-Inc/TileDB-R/issues/25). We will eventually use [contextvars](https://docs.python.org/3/library/contextvars.html) and change the keyword arg default from a single global to a pull from a named contextvar, which would allow an API like:

```
with tiledb.Ctx():
    ... all code here calls automatically gets the new context above
```

(unfortunately cvars are only available in Python 3.7)

**Comment by bhgomes** [comment]
Thank you for adding documentation on this. The situation is much clearer now.

> So far I think multiple contexts are mainly used with the C++ API in a multi-threaded, batched-read situation. It will likely not be an issue in routine use, especially from Python, but we do need to support multiple contexts in the API.

I think eventually either the TileDB team or a third-party will want to add something like native asynchronous (`async`/`await`) support for reading, writing, ... etc. Having this technology fully integrated into the Python API would be extremely helpful if not necessary for this. Even support for `concurrent.futures`-like features is something people will want.

I am looking to use TileDB as a central dependency for an upcoming project and I would see a lot of potential/necessity for such features and would love as much access to the underlying machinery as possible from Python.

**Comment by ihnorton** [comment]
> native asynchronous (async/await) support for reading, writing

Yes, definitely on the roadmap (#64). I think the simplest option will be `concurrent.futures`, which is thread-safe, but we might be able to support asyncio too. I'll take a deeper look soon. Python 2 support may not be possible/reliable though (there is https://pypi.org/project/futures/ but I don't know how well it works) -- fortunately the ecosystem seems to quickly be converging on 3 now, ahead of the py2 end-of-life.
