### ISSUE TITLE
Multiple writes to a sparse array with real domain/attribute values

### ISSUE THREAD

**Issue by thompsonab** [TileDB-Inc/TileDB-Py#133]
TileDB: `1.5.0`
TileDB-Py: `0.4.0`

I previously opened #102 and had to take a break to redirect my efforts on another part of our project. Now I'm resuming work on investigating using TileDB(-Py) to store sparse geospatial data.

We have a requirement to support the storage/querying of point cloud data, presumably ingesting LAS/LAZ files and storing them by some means that permits queries for attributes (intensity, etc.) by geospatial coordinates (latitude, longitude, elevation). I'm attempting to use TileDB-Py in conjunction with PDAL for this purpose. Unfortunately, I'm running into issues when I try to write multiple LAS/LAZ files into the same array.

I imagine it very well is an issue with my code and a fundamental lack of knowledge of/experience with TileDB(-Py). My understanding from the documentation is it's entirely possible to perform multiple writes to the same array, as well as storing real domain values (even negative values, though slicing with negative domain values isn't supported in TileDB-Py, last I knew).

Would the inability to write multiple inputs to the same array be due to misconfigured array dimensions (.e.g, `tile` value not being appropriate for the domain range)? Or perhaps the domain (latitude, longitude, elevation) or attribute (intensity, etc.) values being too granular? The resolution of the input LAS/LAZ files can be very fine.

**Comment by normanb** [comment]
:wave: We have added TileDB support natively to PDAL, this functionality is in PDAL master. Point cloud streaming support has been added in a recent PR - https://github.com/PDAL/PDAL/pull/2440.

It should be possible to use `pdal merge` to write multiple inputs to the same array.

We are also currently working on a PR for GDAL to support raster data.

I think PDAL will support your ingestion into TileDB and then you either use TileDB-Py or PDAL filters to query for attributes. 

Let us know if you have any more questions.

**Comment by abthompson** [comment]
My apologies for the very delayed response. I was redirected from that task onto another for a time, so my focus has been elsewhere since then.

:wave: Thank you for your response. I've noticed and tried to learn to use PDAL's support for TileDB, but I'm afraid I might be missing something and could use some clarification. You mentioned using `pdal merge` to combine inputs into a single array - do you mean combining the LA[SZ] files into a TileDB array, or combining TileDB arrays into one?

Would you be able to provide any guidance on how well this method would be expected to scale with inputs, size of inputs, etc.? We're potentially working with a very large number of LA[SZ] files, which in turn could be very large on their own. One example data set could easily be in the range of billions of points, and I imagine we very easily could need to support larger data sets.

**Comment by thompsonab** [comment]
@normanb I was reassigned to other tasks a long time ago and would be happy to close this issue if deemed appropriate

**Comment by normanb** [comment]
@thompsonab Thanks. Let us know if we can help in the future.
