### ISSUE TITLE
ValueError: shape mismatch

### ISSUE THREAD

**Issue by habibutsu** [TileDB-Inc/TileDB-Py#1808]
I try to run [this](https://cloud.tiledb.com/notebooks/details/paul.fisher/485f18ea-6b22-4aeb-800e-070d59c5951b/preview) notebook from documentation, but getting following error:

```
ValueError: shape mismatch; data dimensions do not match the domain given in array schema ((300, 400) != (300, 400, 3))
```

for cell
```python
with tiledb.open(dense_uri, mode='w') as A:
    A[0:px_rows, 0:px_cols] = im
```

tiledb version: 0.21.6

**Comment by habibutsu** [comment]
It reproduce till 0.19.*, in which error changes
```
TileDBError: Error: Internal TileDB uncaught exception; WriterBase: Buffer sizes check failed; Invalid number of cells given for attribute 'rgb' (360000 != 120000)
```

**Comment by ihnorton** [comment]
Hi @habibutsu, apologies for the delay here - I am looking in to this.

**Comment by ihnorton** [comment]
Hi @habibutsu, I've updated the current version of that notebook here: https://cloud.tiledb.com/notebooks/details/TileDB-Inc/b31aedc4-4f43-4287-8e95-fa7774168fc7/preview

with a small change to pass the image array as the expected dtype
```
with tiledb.open(dense_uri, mode='w') as A:
    A[0:152, 0:152] = im.view(A.dtype)
```

Hope this helps, please let us know if not and we'll be happy to reopen/discuss.

(PS: I'm not sure where the `paul.fisher` version is linked in the docs, but please let me know if you recall, so that we may update the link)
