### ISSUE TITLE
Sparse array tiling

### ISSUE THREAD

**Issue by aosterthun** [TileDB-Inc/TileDB-Py#188]
I converted a netCDF file into tileDB. The performance sadly isn't as good as I hoped. I think this is because of the tiling. When creating a SparseArray, do I even need to set the tile param when creating the dimensions or do I just set the tile_capacity in the schema. I would appreciate some insight into tiling strategies for sparse arrays. I am missing code examples in the documentation.

**Comment by stavrospapadopoulos** [comment]
I would strongly suggest reading [these docs](https://docs.tiledb.io/en/stable/tutorials/tiling-sparse.html) on sparse tiling.

In summary, the following hold for sparse arrays:

- The **space tiling**, determined by the tile extents set upon creating the dimensions, shapes the *global order* of the sparse cells, which in turn determines how cells are grouped into data tiles. These should follow your access patterns; if you slice mainly square-like regions, set equal tile extents per dimension, and make them as big as your typical slice. Similarly, if you favor one dimension over the other (i.e., if your slices are elongated along a dimension), then set the tile extent of that dimension longer than that of the other.

- The **tile capacity**, set in the array schema, determines how many cells will be grouped in a data tile. Note that a data tile is the atomic unit of compression. Any value between 100K and 10M should be fine (so that compression is effective, and IO latency is amortized), but it may take a bit of fine-tuning for each application.

As an additional remark, please note that it may or may not be beneficial to model your array as sparse. I would experiment with both following netCDF's dense array modeling in TileDB, as well as the sparse alternative, in order to see which one performs better for your application. Your dataset must be really sparse in order to justify the extra overhead of the sparse arrays from materializing the coordinates of the non-empty cells, plus all the in-memory ND indices.

If you continue to experience performance problems, please send us your array schema and perhaps a sample of your dataset. We'd be happy to take a look.

**Comment by aosterthun** [comment]
I probably do not get it, but does the space tiling not automatically define the tile capacity ? If I got 3 dimensions (dim_1, dim_2, dim_3) I would imagine that my tiles can hold sizeof(dim_1) * sizeof(dim_2) * sizeof(dim_3) elements ? 

When slicing my data I typically want to get all values (dim_2, dim_3) for a given dim_1 when chunking data with dask in xarray I set the chunk size of dim_2 and dim_3 to their respective max number of elements, and dim_1 to a common slice size. I tried applying the same approach onto TileDBs space tiling but could not get it to work (I get this error: Error: Tile extent check failed; Tile extent exceeds dimension domain range).

**Comment by stavrospapadopoulos** [comment]
Hi Arne,

The confusion here mainly stems from the fact that dense and sparse fragments have some subtle differences with respect to tiling. Note that dense fragments can exist only in dense arrays, a sparse array consists only of sparse fragments, but dense arrays also admit sparse fragments (e.g., in case one needs to write/update non-contiguous cells instead of dense rectangular regions in a dense array).

TileDB distinguishes between the following types of tiles:

- **Space (logical) tiles**: these are oriented by the tile extent defined for each dimension.

- **Data (physical) tiles**: these are groups of *non-empty* cell values that are materialized on the disk (after undergoing compression, encryption and other filters). These are atomic units of compression and IO.

Let's explain the above two types in the case of dense and sparse fragments separately:

- **Dense fragments**:  Since in a dense fragment all cells must have a value, all the cells in a space tile are non-empty. Therefore, TileDB creates a data tile for each space tile, i.e., there is a one-to-one correspondence between a space and a data tile, and `capacity` is irrelevant here. The true capacity of a data tile in dense fragments is equal to `tile_extent_dim_1 * tile_exent_dim_2 * ...`. In fact, we are in the process of renaming `capacity` to `sparse_capacity` to avoid this confusion.

- **Sparse fragments**: The biggest problem in sparse fragments is sparsity and skew. If we kept the same idea as above for dense fragments, i.e., equate a space with a data tile, we could end up having some data tiles that are super sparse and others super dense. This would adversely impact performance. To mitigate this, TileDB allows the user to set a fixed `capacity` for tiles in sparse fragments, such that non-empty cells are always grouped into *equi-sized* data tiles. In this case, there is *no* one-to-one correspondence between a space and a data tile. Instead, a space tile only helps in sorting the non-empty cells in some global order (the docs have more details about that), and TileDB then chops this linear sequence of non-empty cells into fixed-sized data tiles of capacity equal to `capacity`. 

I hope the above helps.

**Comment by ihnorton** [comment]
Closing for now, please re-open/comment if needed, we are happy to reopen and additional details. Also note that @stavrospapadopoulos did a large rework of the documentation recently, including some clarifications on these aspects. Available at https://docs.tiledb.com/developer/
