### ISSUE TITLE
Sparse array is not open for reading when writing

### ISSUE THREAD

**Issue by manolinux** [TileDB-Inc/TileDB-Py#192]
This code complains for array not being open for reading (previous step).

The array definition is:

       domain = tiledb.Domain(tiledb.Dim(name="cols", domain=(978307200, 4102358400), 
                                                    tile=1000, dtype=np.int64))
        schema = tiledb.ArraySchema(domain=domain, sparse=True,
                            attrs=[tiledb.Attr(name="ndvi", dtype=np.float32),
                                   tiledb.Attr(name="kcb",dtype=np.float32),
                                   tiledb.Attr(name="nn",dtype=np.float32),
                                   tiledb.Attr(name="eto",dtype=np.float32),    
                                   tiledb.Attr(name="trigger",dtype=np.dtype('b'))])
`

What I want to do is, for a given timestamp (dimension cols), write a list of attributes (vegatation indexes).

And when computed those values, the code that tries to write today's recordings is:

```
   #TiledDB writing
    with tiledb.SparseArray(grupo_parcela, mode='w') as parcelaAttrsW:                      
                        parcelaAttrsW[tsHoy]['trigger'] = trigger
                        parcelaAttrsW[tsHoy]['eto']=etoParcela 
 
``` 
So, direct access by indexing for  writing seems to need previous read, and thus makes opening 'w' fail. Should I construct a numpy array first and then write it to file, should it be something like:

```
                      parcelaAttrsW[tsHoy]=full array numpy
```

In my opinion, RW mode is something quite useful that has been requested before:

https://github.com/TileDB-Inc/TileDB-Py/issues/58

Kind regards!

**Comment by stavrospapadopoulos** [comment]
I think there are two different issues here. 

1. Writing **multiple attributes** to an array. Currently, when writing to an array, you need to provide **all** attributes as a dictionary of numpy arrays. You can find more details [here](https://docs.tiledb.io/en/stable/tutorials/multi-attribute-arrays.html#writing-to-the-array). Therefore, you need:
```
parcelaAttrsW[tsHoy] = {"trigger": trigger, "eto": etoParcela, ... <all othe attributes here>}
```

2. **Read-Write mode**. Currently, we support opening an array object either in read or write mode. However, TileDB allows you to open the same array in **both** read and write mode, but using two different array objects (one with `mode ='r'` and one with `mode='w'`). This decision was taken in order to simplify the consistency semantics; when opening an array for reading, TileDB "views" only writes that happened at or before the timestamp the array is getting opened at. If we mix reads and writes in the same object, these semantics can become confusing. We continue to consider the read-write mode though and hope to add it in the future with some clear semantics.

Could you please send us the exact error message you are getting for (1) above, as I think it is confusing and we could improve it.

**Comment by manolinux** [comment]
Hi, what i'm trying to do is updating one register for one given timestamp (tsHoy = timestamp for today). Every "register"has some attributes: ndvi, kcb, etctera.

So, acording to your above comment, every "attribute" must be a numpy array, containing some values for every attribute?  (In this case, just one, today's value)

Modifying accordingly, I get the same error as before:
```
 parcelaAttrsW[tsHoy] =  {'ndvi': np.array((ndviMedian))}
  File "tiledb\libtiledb.pyx", line 4715, in tiledb.libtiledb.SparseArray.__setitem__
  File "tiledb\libtiledb.pyx", line 4655, in tiledb.libtiledb.index_domain_coords
TypeError: len() of unsized object
len() of unsized object
```
Think there's something I'm not understanding properly ... 

Thanks  a lot for your help!

**Comment by ihnorton** [comment]
Hi @manolinux, what is the output of `type(ndviMedian)`?

**Comment by stavrospapadopoulos** [comment]
Here is a more detailed example when you have two attributes `a` and `b` in a sparse array with a single dimension `t`:
```
with tiledb.SparseArray(array_name, mode='w') as A:
    # These are the timestamps you would like to write at: 1, 5, 6
    t = [1, 5, 6]
    # These are the values for attribute "a" and "b" at timestamps 1, 5, 6, respectively
    a = np.array(([1, 2, 3]));
    b = np.array(([3, 3, 10]));
    # This is how you write
    A[t] = {"a":a, "b":b}
```

The above will create the following sparse cells in `A` (recall, `t` is the dimension, and `a` and `b` are the attributes):
```
t=1, a=1, b=3
t=5, a=2, b=3
t=6, a=3, b=10
```

My comment above meant to clarify that whenever you write some cells to the array, you need to provide values for **all** attributes. In other words, in the above example, `A[t] = {"a":a}` or `A[t] = {"b":b}` or `A[t] = a` or `A[t] = b` would error out - you need to provide values for both `a` and `b`.

**Comment by manolinux** [comment]
Thanks to everyone for clues. The following message:

```TypeError:` len() of unsized object
len() of unsized object```
seems to appear when in the left hand side of the assignment of an array

A[t] = ...

t is not a list-like object. So, for my assigment I should have done something like

```
timestamps = [tsHoy]
parcelaAttrsW[ timestamps] =  whatever ...
```

Now I'm having other trouble but think has to do with folder permissions in Windows.

Kind regards!
