### ISSUE TITLE
ast.Bytes Deprecation warning

### ISSUE THREAD

**Issue by hobu** [TileDB-Inc/TileDB-Py#1967]
Some Python tiledb usage is noisy now due to a deprecation warning...

```
\tiledb\query_condition.py:19: DeprecationWarning: ast.Bytes is deprecated and will be removed in Python 3.14; use ast.Constant instead
    ast.Name, ast.Constant, ast.Call, ast.Num, ast.Str, ast.Bytes
```

**Comment by kounelisagis** [comment]
Hey @hobu,

what are you versions:
- Python
- core TileDB library: `tiledb.libtiledb.version()`
- TileDB-py package: `tiledb.version()`

**Comment by hobu** [comment]
<img width="273" alt="image" src="https://github.com/TileDB-Inc/TileDB-Py/assets/87751/b85514f4-5aa8-456e-a9fb-1f70da276a62">

**Comment by kounelisagis** [comment]
Official support for **Python 3.12** for TileDB-Py began with version [`0.29.0`](https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.29.0). The warnings you mentioned should have been fixed by this: https://github.com/TileDB-Inc/TileDB-Py/pull/1959/commits/8d1d337928376692ea1b31e5dfb4435443897e95.
Give version `0.29.0` a try (Windows wheels are now available).
