### ISSUE TITLE
Tiledb install in windows environment

### ISSUE THREAD

**Issue by moko-345** [TileDB-Inc/TileDB-Py#314]
I can't install using "conda install -c conda-forge tiledb-py" command.
Any idea to solve the problem?
I use anaconda3 in windows 8.
Followings are the messages from the prompt.

```
(base) PS C:\Users\xxx>> conda install -c conda-forge tiledb-py
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining matplotlib-base:   1%|█                                                                            | 4/301 [00:04<03:45,  1.32it/s]-Examining nose:   3%|██▎                                                                                     | 8/301 [00:55<55:29, 11.36s/it]-Examining cycler:  11%|█████████▌                                                                           | 34/301 [04:23<57:03, 12.82s/it]/Examining qtawesome:  17%|█████████████▌                                                                    | 50/301 [04:56<05:39,  1.35s/it]/Examining backports:  23%|███████████████████                                                               | 70/301 
```

long messages follows after these, which say there are conflicts among packages.

**Comment by ihnorton** [comment]
Hi @moko-345,
Unfortunately, this is a challenge with conda environments because some conflicts are not resolvable when installing into an existing environment. I've just now successfully tested installation in a clean environment, if you are able to try that. If you have any more information which can be shared about the packages you have installed in the existing `(base)`, I might be able to see where the conflict is.

We also now have windows wheels available [from PyPI](https://pypi.org/project/tiledb/) for Python 3.7 and 3.8 (these should work in an existing conda environment - all dependencies are bundled).

**Comment by moko-345** [comment]
I could install using "pip install tiledb" command. 
Thank you very much!
