### ISSUE TITLE
Add attributes or dimensions after creating arrays

### ISSUE THREAD

**Issue by DanielGrigorasch** [TileDB-Inc/TileDB-Py#379]
I could not find a solution to add an attribute (to a schema) or a dimension (to a domain) after the array is beeing created. I know it is difficult with dimensions, but at least adding an attribute should not be a problem.

I found the methods ```addAttribute(Attribute attr)``` in ```ArraySchema.class``` and ```addDimension(Dimension dimension)``` in ```Domain.class``` in the JavaDoc but could not manage to finde those in PythonDoc.

Thanks

**Comment by stavrospapadopoulos** [comment]
Hi @DanielGrigorasch, thanks for pointing this out. It is tracked here: https://feedback.tiledb.com/tiledb-core/p/schema-evolution

Adding an attribute to an existing array is fairly easy from an implementation and on-disk format perspective for TileDB, but we would like to handle this generically under the "schema evolution" umbrella, so that we can continue to provide versioning and time traveling even when the array schema changes. That makes it bit more involved. However, this is has a very high priority in our roadmap, so please stay tuned. 

@ihnorton will follow up on PythonDoc. Please note though that those methods are currently used to construct the _first_ schema upon array creation, not to update the schema after creation. Such API functions will be added once the schema evolution feature is complete.

Thanks again!

**Comment by ihnorton** [comment]
> I found the methods addAttribute(Attribute attr) in ArraySchema.class and addDimension(Dimension dimension) in Domain.class in the JavaDoc but could not manage to finde those in PythonDoc.

Hi @DanielGrigorasch,
These functions are used to build up a schema object one dimension/attribute at a time, but once the array is created, the corresponding schema (currently) cannot be modified.

The equivalent functionality in Python is wrapped into the constructor of the `tiledb.ArraySchema` class: it accepts a `Domain` (constructed from`Dim`ensions) and a list of `Attr`ibutes. Here's an example:

```
dims = [
  tiledb.Dim("d1", (1, 4), 2, dtype=np.int64),
  tiledb.Dim("d2", (1, 4), 2, dtype=np.int64)
]
domain = tiledb.Domain(*dims)

attrs = [
  tiledb.Attr("a1", dtype=float),
  tiledb.Attr("a2", dtype=int)
]

schema = tiledb.ArraySchema(domain=domain, attrs=attrs)

# followed by:
# tiledb.Array.create("/tmp/a111", schema)
```
