### ISSUE TITLE
Is it possible to dynamically change the size of an array after it is created?

### ISSUE THREAD

**Issue by WarBean** [TileDB-Inc/TileDB-Py#450]
In some cases, I cannot pre-determine the exact shape of an array. For example, I am querying from some streaming data, and want to continuously save some array chunks into TileDB. I cannot know in advance how many chunks I will retrieve from the data stream.

Another chunk-wise ndarray package Zarr seems to handle this well. [Zarr supports dynamically resizing or appending to a created array.](https://zarr.readthedocs.io/en/stable/tutorial.html#resizing-and-appending)

I am wondering whether TileDB provides similar APIs or not.

**Comment by stavrospapadopoulos** [comment]
Hi there, 

Apologies for the late reply.

Here is how this works in TileDB:

1. You create the array with an "infinite" domain. For example, if your dimensions are of type `int64`, you can set the dimension domains to `[0, INT64_MAX]` or something similar. Note that this does _not_ populate the array with fill values. It just creates the array schema, which is rapid.
2. You can write in any subarray of this array, anytime. Each write operation will populate only the integral tiles overlapping your write subarray. See [here](https://docs.tiledb.com/main/solutions/tiledb-embedded/internal-mechanics/writing) for more details. Although optional, it is recommended that you write integral tiles (based on the tiling you chose upon array creation) to maximize performance.
3. Use the [non-empty domain](https://docs.tiledb.com/main/solutions/tiledb-embedded/api-usage/reading-arrays/basic-reading#getting-the-non-empty-domain) functionality to see which portion of your array is populated. Use that as a subarray in your read queries (instead of `[:]`) so that you avoid retrieving an enormous number of fill values.

Please feel free to reach out again with further questions.

**Comment by WarBean** [comment]
@stavrospapadopoulos Thanks for your response! However, `non-empty domain` only record the "occupied range", but not the "currently defined range". They are particularily different in sparse array. With this solution, I may need to record the "currently defined range" outside of the array.

**Comment by stavrospapadopoulos** [comment]
The "currently defined" range is the dimension domain which you can retrieve from the array schema:
https://docs.tiledb.com/main/solutions/tiledb-embedded/api-usage/reading-arrays/reading-the-array-schema

**Comment by WarBean** [comment]
Then comes the original question: Is it possible to dynamically change the "currently defined" range like Zarr?

**Comment by stavrospapadopoulos** [comment]
Not today. A workaround (combined with the above approach I shared) is to set the currently defined range in the array metadata: https://docs.tiledb.com/main/solutions/tiledb-embedded/api-usage/array-metadata. You can of course update this at any time, time travel, etc. 

We are adding a schema evolution shortly that will allow you to change the dimension domains at the schema level.

**Comment by WarBean** [comment]
Modifying the metadata seems ok. I will try this. Thanks again!
