### ISSUE TITLE
Unicode dtypes lead to cryptic “Error: Buffer sizes check failed; Invalid number of cells given”

### ISSUE THREAD

**Issue by flying-sheep** [TileDB-Inc/TileDB-Py#493]
reproducible example:

```py
from tempfile import TemporaryDirectory

import numpy
import tiledb

arrays = dict(name_0=numpy.array(['n1', 'n2']))

dom = tiledb.Domain(
    *(tiledb.Dim(domain=(0, i-1), dtype=numpy.int32) for i in next(iter(arrays.values())).shape)
)
attrs = [tiledb.Attr(name=n, dtype=c.dtype) for n, c in arrays.items()]
schema = tiledb.ArraySchema(domain=dom, attrs=attrs)
with TemporaryDirectory() as tmp:
    tiledb.Array.create(tmp, schema)
    with tiledb.open(tmp, 'w') as ta:  # type: tiledb.Array
        ta[...] = arrays
```

raises:

```pytb
Traceback (most recent call last):
  File "/home/phil/.config/JetBrains/PyCharm2020.3/scratches/tdb_bug.py", line 16, in <module>
    ta[...] = arrays
  File "tiledb/libtiledb.pyx", line 4903, in tiledb.libtiledb.DenseArrayImpl.__setitem__
  File "tiledb/libtiledb.pyx", line 4984, in tiledb.libtiledb.DenseArrayImpl._setitem_impl
  File "tiledb/libtiledb.pyx", line 442, in tiledb.libtiledb._write_array
  File "tiledb/libtiledb.pyx", line 506, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 491, in tiledb.libtiledb._raise_tiledb_error
tiledb.libtiledb.TileDBError: [TileDB::Writer] Error: Buffer sizes check failed; Invalid number of cells given for attribute 'name_0' (8 != 2)
```

can be circumvented by doing `tiledb.Attr(name=n, dtype=c.dtype if c.dtype.kind != 'U' else str)`, but that should be done on by tiledb.

**Comment by nguyenv** [comment]
Hi @flying-sheep, 

Thank you for the reproducible example. To give you an update: the problem is two issues with how we handle Unicode strings. 

First, we only handle Unicode that is UTF-8, but NumPy's uses UTF-32. That's why we're seeing this particular error where it's creating 4 times the number of cells than what is expected for this attribute. 

Second, we currently don't support fixed-length cells for strings. Variable-length cells work correctly, regardless of the type of string being used. This is essentially what your workaround does - passing `str` sets cells to be variable-length, whereas passing the `c.dtype` of `<U2` gives a fixed cell length of 2. You are correct that should be done by TileDB as our current documentation states that strings are should automatically set as variable-length.

I am currently discussing two solutions with the team: either we ensure all string attributes be set to variable-length cells, or we go ahead and implement support for fixed-length cells for strings, as we were planning to do so eventually.

I will keep you updated.

**Comment by nguyenv** [comment]
https://github.com/TileDB-Inc/TileDB-Py/pull/495

We have decided to ensure all Unicode string attributes be automatically set to var-length. Your example now works with this latest change. Please let us know if you have any further issues.

**Comment by flying-sheep** [comment]
Perfect, thank you! Also many thanks for explaining the problem and the possible soluitions before fixing it, people do that far too rarely!
