### ISSUE TITLE
Attribute constructor signature does not include all arguments in docs

### ISSUE THREAD

**Issue by stavrospapadopoulos** [TileDB-Inc/TileDB-Py#99]
https://docs.tiledb.io/projects/tiledb-py/en/latest/python-api.html#tiledb.Attr

For instance, `ncells` is listed as argument but does not appear in
`class tiledb.Attr(Ctx ctx, name=u'', dtype=np.float64, compressor=None, filters=None)`

**Comment by ihnorton** [comment]
I think this is a rendering/labeling issue. All of the class-level constructor arguments are listed under `Parameters`:

![image](https://user-images.githubusercontent.com/327706/61238984-da45d800-a70b-11e9-8a35-c428ff634e9d.png)

whereas `ncells` is a read-only property (equivalent to `tiledb_attribute_get_cell_val_num`), because the Attr constructor computes ncells automatically based on the dtype.
![image](https://user-images.githubusercontent.com/327706/61239024-f0539880-a70b-11e9-92c7-8f68788660e8.png)

(Some other gray boxes are class methods).

Please re-open if it still needs improvement!
